workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android APK
        script: |
          # Pass both standard names AND your specific custom names to ensure they get picked up.
          flutter build apk --release \
            --dart-define=GEMINI_API_KEY="$GEMINI_API_KEY" \
            --dart-define=key="$key" \
            --dart-define=SUPABASE_URL="$SUPABASE_URL" \
            --dart-define=super_base_url="$super_base_url" \
            --dart-define=SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" \
            --dart-define=super_base_key="$super_base_key" \
            --dart-define=RC_GOOGLE_KEY="$RC_GOOGLE_KEY" \
            --dart-define=ARC_google="$ARC_google"
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk