workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - google_credentials # Add your keys in Codemagic UI secrets
      vars:
        API_KEY: "YOUR_GEMINI_KEY" # Set this in Codemagic UI Env Vars
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release --dart-define=API_KEY=$API_KEY
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
